name: Test - CI

  # Trigger the workflow on push,   
  # but only for the master branch
on:
  push:
    branches:
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Jenkins execute
        run: curl -I -u admin:111b235163060f2e3cc4c224757297789d "http://1.15.40.38:8080/job/test/build?token=oj139405nasdkasdfjks"
