name: Test - CI

  # Trigger the workflow on push,   
  # but only for the master branch
on:
  push:
    branches:
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Jenkins execute
        run: curl http://1.15.40.38:8080/job/mall/build?token=oj139405nasdkasdfjks
